# Generated by Django 6.0.7 on 2026-07-09 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Clave interna, ej. CAB-001', max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(default='Mazamitla', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('costo_por_dia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacidad_maxima', models.PositiveSmallIntegerField()),
                ('numero_camas', models.PositiveSmallIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cabanas/')),
                ('disponible', models.BooleanField(default=True)),
                ('promedio_calificacion', models.DecimalField(decimal_places=2, default=0, help_text='Se recalcula automáticamente con las reseñas (RF-12)', max_digits=3)),
                ('numero_resenas', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cabaña',
                'verbose_name_plural': 'Cabañas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre de ícono (ej. bi-wifi de Bootstrap Icons)', max_length=50)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('mensaje', models.TextField()),
                ('respuesta', models.TextField(blank=True)),
                ('publicado_en_blog', models.BooleanField(default=False)),
                ('atendido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('cabana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='cabanas.cabana')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('porcentaje_descuento', models.PositiveSmallIntegerField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='cabanas.cabana')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='cabana',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='cabanas', to='cabanas.servicio'),
        ),
    ]
